sudo: false
language: go
go:
    - 1.12.x
git:
    depth: false
install: go get -tags extended -v github.com/gohugoio/hugo
cache:
    directories:
        - $HOME/.cache/go-build
        - $HOME/gopath/src
before_cache:
    - rm -f $HOME/.cache/go-build/log.txt
script:
    - hugo
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_ACCESS_TOKEN
    on:
        branch: master
    local_dir: public
    repo: dai-pch/dai-pch.github.io
    fqdn: blog.daipch.cn
    target_branch: master
    keep_history: true
    email: dpc_work@163.com
    name: Dai, Pengcheng

