sudo: false
language: go
go:
    - 1.12.x
git:
    depth: 1
install: go get -v github.com/gohugoio/hugo
script:
    - hugo
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_ACCESS_TOKEN
    on:
        branch: master
    local_dir: public
    target_branch: gh_pages
    keep_history: true
    email: dpc_work@163.com
    name: Dai, Pengcheng

