baseURL = "https://blog.daipch.cn/"
languageCode = "zh-CN"
title = "东有启明"
theme = "hyde-hyde"
googleAnalytics = "UA-162149996-2"  # UA-XXXXXXXX-X

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 140

[params]
  author = "daipch"
  description = "技术与非技术的感想和随笔"
  keywords = "daipch,blog,博客"
  authorimage = "/img/venus.jpg"
  dateformat = "Jan 2, 2006"
  # busuanzi = true #启用不算子网页统计
  # googleAd = "ca-pub-4031353640611810"  #ca-pub-xxxxxxxxxxxxxx
  # localSearch = true # 启用本地搜索
  mainSections = ["life", "tech"]

  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = "tocbot"  # 是否开启目录

  # sidebar, copyright & license
  copyright = "daipch"
  since = 2020
  license = "CC BY-NC-ND 4.0"
  licenseURL = "https://creativecommons.org/licenses/by-nc-nd/4.0/"
  showBuiltWith = true

  # 代码高亮
  highlightjs = true
  highlightjsstyle = "github"

  # navigation
  postNavigation = false

  ## 配置 utteranc评论,教程参考 https://utteranc.es/
  UtterancesRepo = "dai-pch/dai-pch.github.io"
  UtterancesIssueTerm = "pathname"
  UtterancesTheme = "github-light"

## Social Accounts
[params.social]
    github = "dai-pch"
    # instagram = "<username>"
    # xing = "<username>"
    # linkedin = "<username>"
    # twitter = "<username>"
    # facebook = "<username>"
    # stackoverflow = "<username>"
    # telegram = "<username>"
    # orcid = "<xxxx-xxxx-xxxx-xxxx>"
    email = "dpc_work@163.com"
    # gravatar = "your-email@example.com"

## 友情链接，可以多个

[[params.links]]
  title = "Jiazheng的博客"
  name = "Jiazheng的博客"
  url = "https://liujiazheng.github.io/"

[[params.links]]
  title = "Changsong Zhang的博客"
  name = "Changsong Zhang的博客"
  url = "https://davidzhangbuaa.github.io/"

## 侧边栏广告位
# [[params.ads]]
#   title = "【2019双12】ALL IN CLoud 低至1折"
#   url = "https://www.aliyun.com/minisite/goods?userCode=jdg9oj97&share_source=copy_link"
#   img = "https://img.alicdn.com/tfs/TB1_rYHo7P2gK0jSZPxXXacQpXa-690-388.jpg"

## 配置网站菜单

[menu]

  [[menu.main]]
    identifier = "life"
    name = "🍩 生活"
    url = "/life/"
    weight = 100

  [[menu.main]]
    identifier = "tech"
    name = "🖥️ 技术"
    url = "/tech/"
    weight = 200

  [[menu.main]]
    identifier = "archives"
    name = "📚 归档"
    url = "/archives/"
    weight = 300

  [[menu.main]]
    identifier = "about"
    name = "🤪 关于"
    url = "/about/"
    weight = 400

