baseURL = "https://blog.daipch.cn"
languageCode = "zh-CN"
title = "博客名待定"
theme = "maupassant"
googleAnalytics = "UA-162149996-2"  # UA-XXXXXXXX-X

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 140

# disqusShortname = "yourdiscussshortname"  ## 是否开启disqus评论，不要和utteranc同时开启

[author]
  name = "daipch"

[params]
  author = "daipch"
  subtitle = "技术与非技术的感想和随笔"
  keywords = "daipch,博客"
  description = ""
  busuanzi = true #启用不算子网页统计
# googleAd = "ca-pub-4031353640611810"  #ca-pub-xxxxxxxxxxxxxx
  localSearch = true # 启用本地搜索

  # 这里我存放在了主题的static文件夹里，根目录的似乎也可以
  customCSS = ['douban.css', 'other.css']
  # if ['custom.css'], load '/static/css/custom.css' file
  customJS = ['douban.js']
  # if ['custom.js'], load '/static/js/custom.js' file

  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = true  # 是否开启目录

## 友情链接，可以多个

[[params.links]]
  title = "Jiazheng的博客"
  name = "Jiazheng的博客"
  url = "https://liujiazheng.github.io/"

[[params.links]]
  title = "Changsong Zhang的博客"
  name = "Changsong Zhang的博客"
  url = "https://davidzhangbuaa.github.io/"

## 侧边栏广告位
# [[params.ads]]
#   title = "【2019双12】ALL IN CLoud 低至1折"
#   url = "https://www.aliyun.com/minisite/goods?userCode=jdg9oj97&share_source=copy_link"
#   img = "https://img.alicdn.com/tfs/TB1_rYHo7P2gK0jSZPxXXacQpXa-690-388.jpg"

## 配置 utteranc评论,教程参考 https://utteranc.es/
[params.utteranc]
  enable = true
  repo = "dai-pch.github.io" ##换成自己得
  issueTerm = "pathname"
  theme = "github-light"

## 开启版权声明，协议名字和链接都可以换
[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

## 配置代码高亮
[markup]
  [markup.highlight]
    lineNos = true
    style = "github"

## 配置网站菜单

[menu]

  [[menu.main]]
    identifier = "life"
    name = "生活"
    url = "/life/"
    weight = 1

  [[menu.main]]
    identifier = "tech"
    name = "技术"
    url = "/tech/"
    weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4

